import type { Metadata } from "next";
import Sidenav from './components/sidenav'
import Footer from './components/footer'
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/irans.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          {/* <div className="w-full flex-none md:w-64">
            <Sidenav />
          </div> */}
          <div className="flex-grow  md:overflow-y-auto ">{children}
          <Footer/>
          </div>
        </div>


        </body>
    </html>
  );
}
